FROM openjdk:8-jdk-slim
VOLUME /tpm
ADD target/agrostok-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=prod", "-jar", "/app.jar"]