ALTER TABLE `product` CHANGE COLUMN `value` `value` DECIMAL(18,2) NOT NULL ;
ALTER TABLE `sale` CHANGE COLUMN `value` `value` DECIMAL(18,2) NOT NULL ;
ALTER TABLE `sale_product` CHANGE COLUMN `total` `total` DECIMAL(18,2) NOT NULL ;